### ISSUE TITLE
Cannot configure email settings - "from" address invalid while it is

### ISSUE THREAD

**Issue by superseby2** [pachno/pachno#17]
When configuring my email communication settings. 

All is good when I save. 

When I try to test-send an email I have a error message complaining about the from email address. 
![image](https://user-images.githubusercontent.com/32198925/139462405-2d678a71-3166-425b-ac42-17583ac17ecc.png)

**Comment by jagansankara** [comment]
any update on this bug?

**Comment by zegenie** [comment]
This error seems to be because there is no email address registered to your account, so when the test mail is going out, it doesn't know where to send it. This only happens if you don't provide an email address during setup, or manually removes the email address in the database. 

The error message should of course reflect that, but in this case we'll simply disable the button until the profile is updated with a valid email address. Fix coming.
